# Generated by Django 3.2.7 on 2021-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
